"""modify credit plan table

Revision ID: 42cf5c77a5e5
Revises: 620d2142188e
Create Date: 2025-05-27 17:00:29.504250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "42cf5c77a5e5"
down_revision: Union[str, None] = "620d2142188e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("payment_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("success", "failed", "refunded", "pending", name="paymentstatus"),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["credit_orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_history_payment_id"),
        "payment_history",
        ["payment_id"],
        unique=False,
    )
    op.add_column("credit_plans", sa.Column("credits", sa.Integer(), nullable=True))
    op.add_column("credit_plans", sa.Column("price", sa.Integer(), nullable=True))
    op.drop_column("credit_plans", "price_in_rupees")
    op.drop_column("credit_plans", "credit_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_plans",
        sa.Column("credit_amount", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "credit_plans",
        sa.Column("price_in_rupees", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("credit_plans", "price")
    op.drop_column("credit_plans", "credits")
    op.drop_index(op.f("ix_payment_history_payment_id"), table_name="payment_history")
    op.drop_table("payment_history")
    op.execute("DROP TYPE IF EXISTS paymentstatus;")
    # ### end Alembic commands ###
