"""create credit_plan and credit_order table

Revision ID: 620d2142188e
Revises: a96b1891faed
Create Date: 2025-05-27 13:47:26.082476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "620d2142188e"
down_revision: Union[str, None] = "a96b1891faed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credit_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("credit_amount", sa.Integer(), nullable=False),
        sa.Column("price_in_rupees", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "credit_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "razorpay_order_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("credits_requested", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "currency", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("created", "attempted", "paid", "failed", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credit_orders_razorpay_order_id"),
        "credit_orders",
        ["razorpay_order_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_credit_orders_razorpay_order_id"), table_name="credit_orders"
    )
    op.drop_table("credit_orders")
    op.drop_table("credit_plans")
    op.execute("DROP TYPE IF EXISTS orderstatus;")
    # ### end Alembic commands ###
